ekz/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekz.views import ListeExamens, VoirExamen, liste_alpha_examens, accueil, ListeTubes, ListeBons, ListePrelevements, recherche

from django.contrib.auth.decorators import  permission_required


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

app_name = 'ekz'

urlpatterns =[
    # La liste des examens (tous)
    url(r'^$', ListeExamens.as_view(paginate_by=10), name='liste_examens'),

    # La liste des tubes (tous)
    url(r'^recueils/$', ListeTubes.as_view(), name='liste_tubes'),

    # La liste des bons (tous)
    url(r'^formulaires_de_prescription/$', ListeBons.as_view(), name='liste_bons'),

    # La liste des prelevements (tous)
    url(r'^aide_au_prelevement/$', ListePrelevements.as_view(), name='liste_prelevements'),

    # Page d'un examen
    url(r'^voir/(?P<pk>\d+)$', VoirExamen.as_view(),name='voir_examen'),

    # Liste alphabétique par lettre
    url(r'^commencent_par_(?P<lettre>.+)/$', liste_alpha_examens, name='liste_alpha_examens'),   # def liste_alpha_examens dans views.py

    # Page de recherche
    url(r'^rechercher/$', recherche, name='recherche'),

    # OpenSearch.xml
    url('^opensearch.xml$', TemplateView.as_view(template_name='opensearch.xml'), name='opensearch'),

]

ekzamenoj/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekzamenoj import configlocale
from ekz.views import accueil
from django.contrib.auth.views import login, logout


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns =[
    # Examples:
    # url(r'^$', 'ekzamenoj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page d'accueil (i.e. « home »)
    url(r'^$', accueil, name='accueil'),

    url('^examens/', include('ekz.urls')),
    url('^page', include('pages.urls')),
    url('^patient/', include('patients.urls')),

    url(r'^summernote/', include('django_summernote.urls')),

    # Admindoc
    url(r'^' + settings.ADMIN_URL + '/doc/', include('django.contrib.admindocs.urls')),

    url(r'^' + settings.ADMIN_URL + '/', include(admin.site.urls)),

    # Login à part (provisoire ?)
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),

    # Déconnexion (nécessaire pour les utilisateurs n'ayant pas le statut équipe)
    url(r'^logout/$', logout, {'next_page': 'accueil'}, name='logout'),

    # Page test presc
    #url(r'^prescription/$', prescrire, name='prescrire'),

    # Fichiers robots.txt
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if configlocale.CONFIG_LOCALE['VOIR_PRESCRIPTIONS'] == True:
    urlpatterns +=[ 
        url('^prescriptions/', include('presc.urls')),
        ]

patients/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url



from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

#from django.contrib.auth.decorators import  permission_required


from patients.views import PatientCreate, PatientView, Liste, recherche


app_name = "patients"
urlpatterns = [
       # La liste des patients
       #url(r'^$',Liste.as_view(), name='liste_patients'),

       # Page de recherche
       url(r'^$', recherche, name='recherche'),
       #url(r'^rechercher/$', recherche, name='recherche'),

       # Créer un nouveau patient
       url(r'^creer$', PatientCreate.as_view(), name='creer_patient'),

       # Voir le détail d'un patient
       url(r'^voir/(?P<pk>\d+)$', PatientView.as_view(), name='voir_patient'),


       ]

presc/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.decorators import  permission_required

from presc.views import voir, Liste, prescrire, en_cours, vider, valider, enlever_examen, associer_patient, enlever_patient, eti_presc, prescrire_bilan, prelever, envoyer, recevoir


app_name = "presc"
urlpatterns = [
       # La liste des prescriptions (tous)
       url(r'^$', permission_required('presc.view_prescriptions',raise_exception=True)(Liste.as_view()), name='liste'),

       # Page d'une prescription
       url(r'^(?P<id>\d+)$', permission_required('presc.view_prescriptions',raise_exception=True)(voir), name='voir'),

       # PDF des étiquettes prescription
       url(r'^etiquettes/(?P<pk>\d+)\.pdf$', permission_required('presc.view_prescriptions',raise_exception=True)(eti_presc), name='etiquettes'),

       # Ajouter à une prescription
       url(r'^prescrire/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire), name='prescrire'),

       # Ajouter un bilan à une prescription
       url(r'^prescrire/bilan/(?P<bilan_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire_bilan), name='prescrire_bilan'),

       # Enlever d'une prescription
       url(r'^enlever/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_examen), name='enlever_examen'),

       # Enlever le patient de la prescription en cours de saisie (doit être déclaré avant l'attribution)
       url(r'^patient/enlever$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_patient), name='enlever_patient'),

       # Attribuer une prescription à un patient
       url(r'^patient/(?P<patient_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(associer_patient), name='associer_patient'),

       # Détail de la prescription en cours de saisie
       url(r'^voir$', permission_required('presc.create_prescriptions',raise_exception=True)(en_cours), name='prescription'),

       # Vider la prescription en cours de saisie
       url(r'^vider$', permission_required('presc.create_prescriptions',raise_exception=True)(vider), name='vider'),

       # Valider la prescription en cours de saisie
       # Le décorateur de permission ne peut pas être ici (pourquoi ?) il est donc dans views.py
       url(r'^valider$', valider, name='valider'),
       #url(r'^valider$', permission_required('presc.create_prescriptions',raise_exception=True)(valider), name='valider'),

       # Prélever une prescription
       url(r'^prelever/(?P<prescription_id>\d+)$', permission_required('presc.prelever_prescriptions',raise_exception=True)(prelever), name='prelever'),

       # Envoyer une prescription
       url(r'^envoyer/(?P<prescription_id>\d+)$', permission_required('presc.envoyer_prescriptions',raise_exception=True)(envoyer), name='envoyer'),

       # Recevoir une prescription
       url(r'^recevoir/(?P<prescription_id>\d+)$', permission_required('presc.recevoir_prescriptions',raise_exception=True)(recevoir), name='recevoir'),

       ]

patients/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

#class Tracabilites(models.Model):
#    date = models.DateTimeField(verbose_name=u"Date", auto_now_add=True,)
#    description = models.CharField(verbose_name=u'Description', max_length=255)
#    def __str__ (self):
#        return self.date
#    class Meta:
#        verbose_name=u'Traçabilité'
#        verbose_name_plural=u'Traçabilités'


class Civilites(models.Model):
    abbreviation = models.CharField(max_length=5, unique=True, null=False, verbose_name=u'Abbréviation')
    nom = models.CharField(max_length=50, unique=True, null=False, verbose_name=u'Nom complet')
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now_add=True,)
    def __str__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Civilité"
        verbose_name_plural=u"Civilités"

class Etablissements(models.Model):
    nom = models.CharField(max_length=255,verbose_name=u'Nom')
    description = models.CharField(max_length=255, verbose_name=u'Description')
    def __str__ (self):
        return self.nom
    class Meta:
        verbose_name=u'Établissement'
        verbose_name_plural=u'Établissements'


class Patients(models.Model):
    SEXE = (
        (0,u'Indéterminé'),
        (1,u'Féminin'),
        (2,u'Masculin'),
    )
    #civilite = models.ForeignKey(Civilites)
    nom_usage = models.CharField(max_length=255, verbose_name=u"Nom d'usage")
    nom_naissance = models.CharField(max_length=255, verbose_name=u"Nom de naissance", blank=True)
    prenom = models.CharField(max_length=255, verbose_name=u'Prenom')
    sexe = models.IntegerField(verbose_name=u'Sexe', null=False, choices=SEXE)
    ddn = models.DateField(verbose_name=u"Date de naissance")
    #adresse = models.TextField(verbose_name=u'Adresse', blank=True)
   # num_unique = models.BigIntegerField(verbose_name=u'Identifiant unique du patient (???)', null=True,blank=True)
   # tracabilite = models.OneToOneField(Tracabilites, verbose_name=u"Tracabilite", blank=True, null=True)

    def get_absolute_url(self):
        return reverse('voir_patient', kwargs={'pk': self.pk})

    def __str__ (self):
        if self.sexe == 1:
            self.ne = u"née"
        else:
            self.ne = u"né"
        if self.nom_naissance != self.nom_usage or self.nom_naissance:
            return u"{0} {1} {2} {3} le {4}".format(self.prenom,self.nom_usage, self.ne, self.nom_naissance, self.ddn)
        else:
            return u"{0} {1} {2} le {3}".format(self.prenom,self.nom_usage, self.ne, self.ddn)
    class Meta:
        verbose_name=u"Patient"
        verbose_name_plural=u"Patients"


class Services(models.Model):
    code = models.CharField(max_length=50, verbose_name=u'Code')
    nom = models.CharField(max_length=255, verbose_name=u'Nom')
    etablissement = models.ForeignKey(Etablissements, verbose_name=u'Etablissement')
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now_add=True,)
    def __str__ (self):
        return u'{0} / {1} ({2})'.format(self.etablissement,self.nom, self.code)
    class Meta:
        verbose_name=u'Service'
        verbose_name_plural=u'Services'

class Sejours(models.Model):
    patient = models.ForeignKey(Patients)
    numero = models.BigIntegerField(verbose_name=u'Numéro de séjour')
    ipp = models.BigIntegerField(verbose_name=u'Identifiant permanant du patient (IPP)', blank=True)
    service = models.ForeignKey(Services, verbose_name=u"Service")
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now_add=True,)

    def __str__ (self):
        return u'{0} / {1}'.format(self.patient,self.service)
    class Meta:
        verbose_name=u'Séjour'
        verbose_name_plural=u'Séjours'

patients/views.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from patients.models import Patients
from patients.forms import RecherchePatientsForm
from ekz.views import Alphabet
from presc.models import Prescriptions
from pages.views import ListeDesPages

class Liste(ListView):
    """Liste des patients dans la base"""
    model = Patients
    context_object_name= "liste_patients" # ==> Ce que l'on retrouve dans le template'
    template_name = "liste.html"
    def get_context_data(self, **kwargs):
        context = super(Liste, self).get_context_data(**kwargs)
        context['pages'] = ListeDesPages()
        context['alphabet'] = Alphabet()
        return context


class PatientCreate(CreateView):
    """
    Classe générique de création d'un patient
    """
    model = Patients
    fields = [ 'nom_usage', 'nom_naissance', 'prenom', 'ddn','sexe' ]
    template_name = "patients_form.html"



class PatientView(DetailView):
    """
    Classe générique de visualisation d'un patient
    """
    model = Patients
    template_name = "voir_patient.html"
    def get_context_data(self, **kwargs):
        context = super(PatientView, self).get_context_data(**kwargs)
        context['pages'] = ListeDesPages()
        context['alphabet'] = Alphabet()
        context['prescriptions'] = Prescriptions.objects.filter(patient=context['patients'])
        return context


def recherche(request):
    '''Recherche de patients '''
    if len(request.POST) > 0:
        form = RecherchePatientsForm(request.POST)
        if form.is_valid():
            ddn = form.cleaned_data['ddn']
            Resultats = Patients.objects.filter(ddn=ddn).order_by('nom_usage')
    else:
        form = RecherchePatientsForm()
    return render(request, 'recherche_patients.html', locals())

patients/templates/liste.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="liste_patients"{% endblock %}
{% block header %}
<h3>Liste des patients enregistrées dans la base</h3>
{% endblock %}

{% block content %}
<h4>Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !</h4>

<table class="liste_patients">
    <thead>
        <tr>
            <td>Numéro Unique</td>
            <td>Nom</td>
            <td>Nom de jeune fille</td>
            <td>Prénom</td>
            <td>DDN</td>
            <td>Sexe</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    {% for patient in liste_patients %}
    <tbody>
        <tr>
            <td>N/A</td>
            <td>{{ patient.nom }}</td>
            <td>{{ patient.nom_jf }}</td>
            <td>{{ patient.prenom }}</td>
            <td>{{ patient.ddn }}</td>
            <td>{{ patient.get_sexe_display }}</td>
            <td><a href="{% url 'presc:associer_patient' patient.id %}"><img src="{% static 'img/yes.png' %}" alt="Attribuer la prescription au patient" title="Attribuer la prescription au patient"></a></td>
            <td><a href="{% url 'patients:voir_patient' patient.id %}"><img src ="{% static 'img/aide.png' %}" alt="Voir les détails" title="Détails…"></a></td>
        </tr>
    </tbody>
    {% empty %}
    <tbody>
        <tr>
            <td colspan="7">Rien n'a été saisi pour l'instant.</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
<p>
<a href="{% url "patients:creer_patient" %}"><img src="{% static 'img/ajouter.png' %}" title="Ajouter un patient" alt=" + "></a>
</p>
{% endblock %}

patients/templates/patients_form.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="creer_patient"{% endblock %}
{% block title %} Créer un nouveau patient {% endblock %}
{% block header %}
<h3>Créer un patient</h3>
{% endblock %}

{% block content %}

<fieldset>
    <legend><img src="{% static "img/patient.png" %}" alt="Patient"></legend>
           {% if form.errors %}
        <p class="erreur">Le formulaire contient des erreurs</p>
    {% endif %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Créer" />
    </form>
</fieldset>


<script language="JavaScript">
document.getElementById('id_nom').focus();
</script>
{% endblock %}

patients/templates/recherche_patients.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="rechercher_patient"{% endblock %}
{% block title %}Rechercher un patient {% endblock %}
{% block header %}
<h3>Rechercher un patient</h3>
{% endblock %}

{% block content %}
<fieldset>
    <legend><img src="{% static "img/patient.png" %}" alt="Patient"></legend>
           {% if form.errors %}
        <p class="erreur">Le formulaire contient des erreurs</p>
    {% endif %}
    <form method="post" action="{% url 'patients:recherche' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Rechercher" />
    </form>
</fieldset>

{% if Resultats %}
<table class="liste_patients">
    <thead>
        <tr>
            <td>Numéro Unique</td>
            <td>Nom</td>
            <td>Nom de naissance</td>
            <td>Prénom</td>
            <td>DDN</td>
            <td>Sexe</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    {% for patient in Resultats %}
    <tbody>
        <tr>
            <td>N/A</td>
            <td>{{ patient.nom_usage }}</td>
            <td>{{ patient.nom_naissance }}</td>
            <td>{{ patient.prenom }}</td>
            <td>{{ patient.ddn }}</td>
            <td>{{ patient.get_sexe_display }}</td>
            <td><a href="{% url 'presc:associer_patient' patient.id %}"><img src="{% static 'img/yes.png' %}" alt="Attribuer la prescription au patient" title="Attribuer la prescription au patient"></a></td>
            <td><a href="{% url 'patients:voir_patient' patient.id %}"><img src ="{% static 'img/aide.png' %}" alt="Voir les détails" title="Détails…"></a></td>
        </tr>
    </tbody>
    {% empty %}
    <tbody>
        <tr>
            <td colspan="7">Rien n'a été saisi pour l'instant.</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% else %}
<table class="liste_patients">
    <tbody>
        <tr>
            <td colspan="8">Rien trouvé :-(</td>
        </tr>
    </tbody>
</table>
{% endif %}
<p>
<a href="{% url "patients:creer_patient" %}"><img src="{% static 'img/ajouter.png' %}" title="Ajouter un patient" alt=" + "></a>
<script language="JavaScript">
document.getElementById('id_ddn').focus();
</script>
{% endblock %}

patients/templates/voir_patient.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="voir_patient"{% endblock %}
{% block header %}
<h3>Détail d'un patient</h3>
{% endblock %}

{% block content %}
<h4>Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !</h4>

<table class="details_patient">
    <tr>
        <th>Nom</th>
        <td>{{ patients.nom_usage }}</td>
    </tr>
    <tr>
        <th>Nom de naissance</th>
        <td>{{ patients.nom_naissance }}</td>
    </tr>
    <tr>
        <th>Prénom</th>
        <td>{{ patients.prenom }}</td>
    </tr>
    <tr>
        <th>Sexe</th>
        <td>{{ patients.get_sexe_display }}</td>
    </tr>
    <tr>
        <th>Date de naissance</th>
        <td>{{ patients.ddn }}</td>
    </tr>
    <tr>
        <td colspan="2"><a href="{% url 'presc:associer_patient' patients.id %}">Attribuer la prescription au patient</a></td>
    </tr>
</table>


<table class="liste_prescriptions">
    <thead>
        <tr>
            <th>Numéro</th>
            <th>Etiquettes</th>
            <th>Date de prescription</th>
            <th>Prescripteur</th>
            <th>Date d'exécution</th>
            <th>Détails</th>
        </tr>
    </thead>
    <tbody>
        {% if prescriptions %}
        {% for prescription in prescriptions %}
        <tr>
            <td></td>
            <td><a href="{% url 'presc:etiquettes' prescription.id %}"><img src="{% static 'img/etiquettes.png' %}" alt="Etiquettes" title="Éditer les étiquettes"></a></td>
            <td>{{ prescription.date_crea }}</td>
            <td>{{ prescription.prescripteur.first_name }} {{ prescription.prescripteur.last_name }}</td>
            <td>{{ prescription.date_exec }}</td>
            <td><a href="{% url 'presc:voir' prescription.id %}"><img src ="{% static 'img/aide.png' %}" alt="Voir les détails" title="Détails…"</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5">
                Rien…
            </td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}