ekz/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekz.views import ListeExamens, VoirExamen, liste_alpha_examens, accueil, ListeTubes, ListeBons, ListePrelevements, recherche

from django.contrib.auth.decorators import  permission_required


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

app_name = 'ekz'

urlpatterns =[
    # La liste des examens (tous)
    url(r'^$', ListeExamens.as_view(paginate_by=10), name='liste_examens'),

    # La liste des tubes (tous)
    url(r'^recueils/$', ListeTubes.as_view(), name='liste_tubes'),

    # La liste des bons (tous)
    url(r'^formulaires_de_prescription/$', ListeBons.as_view(), name='liste_bons'),

    # La liste des prelevements (tous)
    url(r'^aide_au_prelevement/$', ListePrelevements.as_view(), name='liste_prelevements'),

    # Page d'un examen
    url(r'^voir/(?P<pk>\d+)$', VoirExamen.as_view(),name='voir_examen'),

    # Liste alphabétique par lettre
    url(r'^commencent_par_(?P<lettre>.+)/$', liste_alpha_examens, name='liste_alpha_examens'),   # def liste_alpha_examens dans views.py

    # Page de recherche
    url(r'^rechercher/$', recherche, name='recherche'),

    # OpenSearch.xml
    url('^opensearch.xml$', TemplateView.as_view(template_name='opensearch.xml'), name='opensearch'),

]

ekzamenoj/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekzamenoj import configlocale
from ekz.views import accueil
from django.contrib.auth.views import login, logout


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns =[
    # Examples:
    # url(r'^$', 'ekzamenoj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page d'accueil (i.e. « home »)
    url(r'^$', accueil, name='accueil'),

    url('^examens/', include('ekz.urls')),
    url('^page', include('pages.urls')),
    url('^patient/', include('patients.urls')),

    url(r'^summernote/', include('django_summernote.urls')),

    # Admindoc
    url(r'^' + settings.ADMIN_URL + '/doc/', include('django.contrib.admindocs.urls')),

    url(r'^' + settings.ADMIN_URL + '/', include(admin.site.urls)),

    # Login à part (provisoire ?)
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),

    # Déconnexion (nécessaire pour les utilisateurs n'ayant pas le statut équipe)
    url(r'^logout/$', logout, {'next_page': 'accueil'}, name='logout'),

    # Page test presc
    #url(r'^prescription/$', prescrire, name='prescrire'),

    # Fichiers robots.txt
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if configlocale.CONFIG_LOCALE['VOIR_PRESCRIPTIONS'] == True:
    urlpatterns +=[ 
        url('^prescriptions/', include('presc.urls')),
        ]

patients/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url



from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

#from django.contrib.auth.decorators import  permission_required


from patients.views import PatientCreate, PatientView, Liste, recherche


app_name = "patients"
urlpatterns = [
       # La liste des patients
       #url(r'^$',Liste.as_view(), name='liste_patients'),

       # Page de recherche
       url(r'^$', recherche, name='recherche'),
       #url(r'^rechercher/$', recherche, name='recherche'),

       # Créer un nouveau patient
       url(r'^creer$', PatientCreate.as_view(), name='creer_patient'),

       # Voir le détail d'un patient
       url(r'^voir/(?P<pk>\d+)$', PatientView.as_view(), name='voir_patient'),


       ]

presc/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.decorators import  permission_required

from presc.views import voir, Liste, prescrire, en_cours, vider, valider, enlever_examen, associer_patient, enlever_patient, eti_presc, prescrire_bilan, prelever, envoyer, recevoir


app_name = "presc"
urlpatterns = [
       # La liste des prescriptions (tous)
       url(r'^$', permission_required('presc.view_prescriptions',raise_exception=True)(Liste.as_view()), name='liste'),

       # Page d'une prescription
       url(r'^(?P<id>\d+)$', permission_required('presc.view_prescriptions',raise_exception=True)(voir), name='voir'),

       # PDF des étiquettes prescription
       url(r'^etiquettes/(?P<pk>\d+)\.pdf$', permission_required('presc.view_prescriptions',raise_exception=True)(eti_presc), name='etiquettes'),

       # Ajouter à une prescription
       url(r'^prescrire/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire), name='prescrire'),

       # Ajouter un bilan à une prescription
       url(r'^prescrire/bilan/(?P<bilan_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire_bilan), name='prescrire_bilan'),

       # Enlever d'une prescription
       url(r'^enlever/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_examen), name='enlever_examen'),

       # Enlever le patient de la prescription en cours de saisie (doit être déclaré avant l'attribution)
       url(r'^patient/enlever$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_patient), name='enlever_patient'),

       # Attribuer une prescription à un patient
       url(r'^patient/(?P<patient_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(associer_patient), name='associer_patient'),

       # Détail de la prescription en cours de saisie
       url(r'^voir$', permission_required('presc.create_prescriptions',raise_exception=True)(en_cours), name='prescription'),

       # Vider la prescription en cours de saisie
       url(r'^vider$', permission_required('presc.create_prescriptions',raise_exception=True)(vider), name='vider'),

       # Valider la prescription en cours de saisie
       # Le décorateur de permission ne peut pas être ici (pourquoi ?) il est donc dans views.py
       url(r'^valider$', valider, name='valider'),
       #url(r'^valider$', permission_required('presc.create_prescriptions',raise_exception=True)(valider), name='valider'),

       # Prélever une prescription
       url(r'^prelever/(?P<prescription_id>\d+)$', permission_required('presc.prelever_prescriptions',raise_exception=True)(prelever), name='prelever'),

       # Envoyer une prescription
       url(r'^envoyer/(?P<prescription_id>\d+)$', permission_required('presc.envoyer_prescriptions',raise_exception=True)(envoyer), name='envoyer'),

       # Recevoir une prescription
       url(r'^recevoir/(?P<prescription_id>\d+)$', permission_required('presc.recevoir_prescriptions',raise_exception=True)(recevoir), name='recevoir'),

       ]

presc/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models

from django.contrib.auth.models import User

from ekz.models import Examens
from patients.models import Patients

# Create your models here.

import datetime

class Prescriptions(models.Model):
   # numero = models.IntegerField(verbose_name=u'Numéro unique',)
    prescripteur = models.ForeignKey(User, verbose_name=u"Prescripteur")
    patient = models.ForeignKey(Patients, verbose_name=u'Patient')
    date_exec = models.DateTimeField(verbose_name=u"Date d'éxécution prévue")
    examens = models.ManyToManyField(Examens, verbose_name=u"Examens")
    commentaire = models.TextField(verbose_name=u'Commentaire', null=True, blank=True)
    date_crea = models.DateTimeField(verbose_name=u"Date de création", auto_now_add=True,)
    date_prel = models.DateTimeField(verbose_name=u"Date de prélèvement", null=True, blank=True)
    preleveur = models.ForeignKey(User, verbose_name=u"Préleveur", related_name="preleveur", null=True, blank=True)
    date_depart = models.DateTimeField(verbose_name=u"Date de départ", null=True, blank=True)
    date_arrive = models.DateTimeField(verbose_name=u"Date d'arrivée", null=True, blank=True)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True, blank=True,)
    def __str__ (self):
        return str(self.id)
    class Meta:
        verbose_name=u"Prescription"
        verbose_name_plural=u"Prescriptions"
        permissions = (
              ("view_prescriptions", u"Peut voir les prescriptions"),
              ("create_prescriptions", u"Peut prescrire"),
              ("prelever_prescriptions", u"Peur prélever"),
              ("envoyer_prescriptions", u"Peut envoyer une prescription"),
              ("recevoir_prescriptions", u"Peut recevoir une prescription"),
            )

presc/forms.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import datetime
from django import forms
from presc.models import Prescriptions
from ekz.models import Examens

class ValiderPrescriptionForm(forms.ModelForm):
    """ Formulaire de validation d'une prescription
    """
    date_exec=forms.SplitDateTimeField(initial=datetime.datetime.now, label="Date d'exécution")
    class Meta:
        model = Prescriptions
        exclude = ('date_crea', 'date_modif', 'examens', 'prescripteur', 'patient', 'date_prel', 'preleveur', 'date_depart', 'date_arrive')

presc/templates/examens_prescrits.html
{% load static %}
{% if prescription %}
<ul>
    {% for prescription_ligne in prescription %}
    <li><a href="{% url 'ekz:voir_examen' prescription_ligne.id %}">{{ prescription_ligne|safe }}</a> <a href="{% url 'presc:enlever_examen' prescription_ligne.id %}" title="Retirer de la prescription"><img src="{% static 'img/poubelle.png' %}" alt="Ôter"></a></li>
    {% endfor %}
</ul>
<a href="{% url 'presc:vider' %}"><img src="{% static 'img/poubelle2.png' %}" alt="Vider" title="Vider la prescription"></a>
{% else %}
<p>Il n'y a pas de prescription en cours</p>
{% endif %}
<p>Patient : {% if prescription_patient %} {{ prescription_patient }} <a href="{% url 'presc:enlever_patient' %}" title="Retirer de la prescription"><img src="{% static 'img/poubelle.png' %}" alt="Ôter"></a>{% else %} Aucun patient pour cette prescription. <a href="{% url 'patients:recherche' %}">Sélectionnez un patient</a>{% endif %}</p>

presc/templates/liste_prescriptions.html
{% extends "base.html" %}

{% block idBODY %} id="liste_prescriptions"{% endblock %}
{% block header %}
<h3>Liste des prescriptions enregistrées dans la base</h3>
{% endblock %}

{% block content %}
<ul class="messages">
    <li class=" debug ">
Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !
    </li>
</ul>

<table class="liste_prescriptions">
    <thead>
        <tr>
            <td>Patient</td>
            <td>À faire</td>
            <td>Détails</td>
            <td>Date de saisie</td>
            <td>Saisie par</td>
            <td>Date de la dernière modif</td>
            <td></td>
        </tr>
    </thead>
    {% for prescription in liste_prescriptions %}
    <tbody>
        <tr>
            <td>{{ prescription.patient }}</td>
            <td>{{ prescription.date_exec }}</td>
            <td><a href="{% url 'presc:voir' prescription.id %}">» Voir</a></td>
            <td>{{ prescription.date_crea }}</td>
            <td>{{ prescription.prescripteur.first_name }} {{ prescription.prescripteur.last_name }}</td>
            <td>{{ prescription.date_modif }}</td>
            <td></td>
        </tr>
    </tbody>
    {% empty %}
    <tbody>
        <tr>
            <td colspan="7">Rien n'a été saisi pour l'instant.</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% endblock %}

presc/templates/prescription.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="prescription"{% endblock %}
{% block header %}
<h3>Prescription en cours d'enregistrement</h3>
{% endblock %}

{% block content %}
<ul class="messages">
    <li class=" debug ">
Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !
    </li>
</ul>


{% include 'examens_prescrits.html' %}

{% if prescription and prescription_patient %}
<a href="{% url 'presc:valider' %}"><img src="{% static 'img/ok2.png' %}" alt="Valider" title="Valider la prescription"></a>
{% endif %}
{% endblock %}

presc/templates/prescrire.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="prescription"{% endblock %}
{% block header %}
<h3>Prescription en cours d'enregistrement</h3>
{% endblock %}

{% block content %}
<ul class="messages">
    <li class=" debug ">
Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !
    </li>
</ul>

{% include 'examens_prescrits.html' %}

<fieldset>
    <legend><img src="{% static "img/puzzle.png" %}" alt="Valider la prescription"></legend>
    {% if form.errors %}
        <p class="erreur">Le formulaire contient des erreurs</p>
    {% endif %}
    <form method="post" action="{% url 'presc:valider' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Valider" />
    </form>
</fieldset>
<script>
// Faisons en sorte d'avoir une aide à la saisie de la date
$( "#id_date_exec_0" ).datepicker();
$.datepicker.setDefaults( $.datepicker.regional[ "fr" ] );
</script>

{% endblock %}

presc/templates/voir_prescription.html
{% extends "base.html" %}
{% load static %}
{% block idBODY %} id="voir_prescription"{% endblock %}

{% block header %}
<h3>Prescription numéro {{ prescription.id }} </h3>
{% endblock %}

{% block content %}
<ul class="messages">
    <li class=" debug ">
Avertissement : cet outil, toujours en développement, n'est proposé que pour des tests et ne saurait être utilisé en réel !
    </li>
</ul>


<table>
<tr>
	<td>Prescription</td>
	<td>{{ prescription.id }}</td>
	<td>{{ prescription.date_crea }} par {{ prescription.prescripteur.first_name }} {{ prescription.prescripteur.last_name }}</td>
</tr>
<tr>
	<td>Patient</td>
	<td colspan="2" ><a href="{% url 'patients:voir_patient' prescription.patient.id %}"><img src="{% static 'img/patient.png' %}" alt="Patient" title="Voir les détails du patient"></a> {{ prescription.patient }}</td>
</tr>
<tr>
	<td>Prévu pour le {{ prescription.date_exec  }}</td>
	<td>
    <ul>
    {% if prescription.date_prel != Null %}
    <li>Prélevé : {{ prescription.date_prel }} ({{ prescription.preleveur }})</li>
        {% if prescription.date_depart != Null  %}
            <li>Départ : {{ prescription.date_depart }}</li>
            {% if prescription.date_arrive != Null %}
                <li>Réception : {{ prescription.date_arrive }}</li>
            {% else %}
                {% if perms.presc.recevoir_prescriptions %}
                    <li><a href="recevoir/{{ prescription.id }}">Marquer comme reçu au labo</a></li>
                {% endif %}
            {% endif %}
        {% else %}
            {% if perms.presc.envoyer_prescriptions %}
                <li><a href="envoyer/{{ prescription.id }}">Marquer comme parti</a></li>
            {% endif %}
        {% endif %}
    {% else %}
    {% if perms.presc.prelever_prescriptions %}
        <li><a href="prelever/{{ prescription.id }}">Marquer comme prélevé maintenant par moi</a></li>
    {% endif %}
    {% endif %}
    </ul>
	</td>
	<td>Modification le {{ prescription.date_modif }}</td>
</tr>
<tr>
	<td> Examens</td>
	<td>
    <ul>
        {% for ex in prescription.examens.all %}
        <li><a href='{% url "ekz:voir_examen" ex.id %}'>{{ ex.nom|safe }}</a></li>
        {% empty %}
        <li>Rien à faire (!??)</li>
        {% endfor %}
    </ul>
	</td>
	<td>
        <a title="Voir le détail des pélèvements" href="#oModalprelevement"><img src="{% static 'img/tubes_prelevement.png' %}" alt="Prélèvement" title="Liste des tubes à prélever"></a>
     <a href="{% url 'presc:etiquettes' prescription.id %}"><img src="{% static 'img/etiquettes.png' %}" alt="Etiquettes" title="Éditer les étiquettes"></a>   {% include "omodal_haut.html" with id="oModalprelevement" %}
            {% for prel in prelevement %}
                <ul>
                    <li><em>{{ prel.nom_prel }}</em> : <strong>{{ prel.nbre_tube|floatformat}}</strong> x <img src="{{ MEDIA_URL}}{{ prel.img_tube }}" alt="{{ prel.nom_tube }}" title="{{ prel.nom_tube }}"></li>
                </ul>
            {% endfor %}
        {% include "omodal_bas.html" with id="oModalprelevement" legende="Prélèvements pour la prescription" %}
        <p>
        {% if prescription.commentaire %} {{ prescription.commentaire }} {% endif %}
        </p>
	</td>
</tr>
{% if docjoints %}
<tr>
	<td>Documents à joindre</td>
	<td colspan="2">
    <ul id="fichiers">
        {% for doc in docjoints %}
        <li><a href="{{ MEDIA_URL }}{{ doc.0.fichier }}"><img src="{% static "img/attachment.png" %}" alt="{{ doc.0.nom }}" title="Télécharger"><br><strong>{{ doc.0.nom }}</strong></a><br><em>{{ doc.0.description }}</em></li>
        {% endfor %}
	</td>
    </ul>
</tr>
{% endif %}
</table>




{% endblock %}