ekz/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from views import ListeExamens, VoirExamen, liste_alpha_examens, accueil, ListeTubes, ListeBons, ListePrelevements, recherche

from django.contrib.auth.decorators import  permission_required


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView


urlpatterns = patterns('',
    # La liste des examens (tous)
    url(r'^$', ListeExamens.as_view(paginate_by=10), name='liste_examens'),

    # La liste des tubes (tous)
    url(r'^recueils/$', ListeTubes.as_view(), name='liste_tubes'),

    # La liste des bons (tous)
    url(r'^formulaires_de_prescription/$', ListeBons.as_view(), name='liste_bons'),

    # La liste des prelevements (tous)
    url(r'^aide_au_prelevement/$', ListePrelevements.as_view(), name='liste_prelevements'),

    # Page d'un examen
    #url(r'^voir/(?P<id>\d+)$', voir_examen, name='voir_examen'),
    #url(r'^voir/(?P<pk>\d+)$', permission_required('ekz.view_inactif',raise_exception=True)(VoirExamen.as_view()),name='voir_examen'),
    url(r'^voir/(?P<pk>\d+)$', VoirExamen.as_view(),name='voir_examen'),

    # Liste alphabétique par lettre
    url(r'^commencent_par_(?P<lettre>.+)/$', liste_alpha_examens, name='liste_alpha_examens'),   # def liste_alpha_examens dans views.py

    # Page de recherche
    url(r'^rechercher/$', recherche, name='recherche'),
    # OpenSearch.xml 
    url('^opensearch.xml$', TemplateView.as_view(template_name='opensearch.xml'), name='opensearch'),

)

ekz/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models
#import ekzamenoj.settings

import datetime

from ekzamenoj import localsettings
# Create your models here.

from tttstr import strip_diac

class Tubes(models.Model):
    """ La table Tubes contient l'ensemble des éléments (tubes, flacons...) pouvant être utilisés pour les prélèvements.
    Le champ « ordre de prélèvement » permet de classer les prélèvements dans l'ordre, c'est surtout intéressant pour le prélèvement sanguin.
    La valeur peut-être comprise entre -32768 et 32767, n'hésitez pas à utiliser des valeurs espacées afin de pouvoir intercaler
    facilement un nouveau tube sans avoir à changer tous les nombres.
     """
    nom = models.CharField(verbose_name=u'Nom', max_length=255)
    ordre = models.SmallIntegerField(verbose_name=u'Ordre de prélèvement')
    image = models.ImageField(verbose_name=u"Image/Logo", upload_to="images/tubes/", blank=True)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Tube ou flacon pour le prélèvement"
        verbose_name_plural=u"Tubes ou flacons pour le prélèvement"
        ordering = ['ordre']


class SousTraitants(models.Model):
    """ La table SousTraitants contient l'ensemble des sous-traitants utilisés en liens avec la sous-traitance """
    nom         = models.CharField(verbose_name=u'Nom du sous-traitant', max_length=255)
    description = models.CharField(verbose_name=u'Description', max_length=255, blank=True)
    ville       = models.CharField(verbose_name=u'Ville', max_length=15, blank=True)
    cp          = models.CharField(verbose_name=u'Code postal', max_length=15, blank=True)
    telephone   = models.CharField(verbose_name=u'Numéro de téléphone', max_length=100, blank=True)
    courriel    = models.EmailField(verbose_name=u'Adresse de courriel', blank=True)
    url         = models.URLField(u'Site Internet', blank=True)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Sous-traitant"
        verbose_name_plural=u"Sous-traitants"

class Transporteurs(models.Model):
    """ La table Transporteurs contient l'ensemble des intermédiaires à la sous-traitance : les transporteurs """
    nom         = models.CharField(verbose_name=u'Nom du transporteur', max_length=255)
    description = models.CharField(verbose_name=u'Description', max_length=255, blank=True)
    ville       = models.CharField(verbose_name=u'Ville', max_length=255, blank=True)
    cp          = models.CharField(verbose_name=u'Code postal', max_length=255, blank=True)
    telephone   = models.CharField(verbose_name=u'Numéro de téléphone', max_length=100, blank=True)
    courriel    = models.EmailField(verbose_name=u'Adresse de courriel', blank=True)
    url         = models.URLField(u'Site Internet', blank=True)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Transporteur"
        verbose_name_plural=u"Transporteurs"


class SousTraitance(models.Model):
    """ La table SousTraitance permet de résumer les conditions de sous-traitance.
    Elle est liée aux tables SousTraitants, Transpoteurs, Temperatures et Stockages.
    Un seul examen est lié à un seul mode de soustraitance, les infos sont  donc spécifiques """
    soustraitant = models.ForeignKey(SousTraitants, verbose_name=u"Sous-traitant", on_delete=models.PROTECT)
    transporteur = models.ForeignKey(Transporteurs, verbose_name=u"Transporteur", blank=True, null=True, on_delete=models.PROTECT)
    temperature  = models.ForeignKey('Temperatures', blank=True, null=True, on_delete=models.PROTECT)
    stockage     = models.ForeignKey('Stockages', blank=True, null=True, on_delete=models.PROTECT)
    url          = models.URLField(verbose_name=u'Liens vers infos externes', blank=True, null=True)
    infos        = models.TextField(verbose_name=u"Informations complémentaires", blank=True, null=True)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__(self):
            return u"Envoyé par {0} vers {1} ({2})".format(self.transporteur,self.soustraitant,self.temperature)
    class Meta:
        verbose_name=u"Sous-traitance"
        verbose_name_plural=u"Sous-traitances"
        permissions = (
            ("view_soustraitance", u"Peut voir la sous-traitance"),
            ("view_soustraitance_details", u"Peut voir les détails de la sous-traitance"),
            )


class Urgences(models.Model):
    """ La table Urgences contient la liste des niveaux d'urgence. Quatre classes CSS sont disponibles pour les illustrer """
    CSS = (
       ('urgence1',u'Urgence 1'),
       ('urgence2',u'Urgence 2'),
       ('urgence3',u'Urgence 3'),
       ('urgence4',u'Urgence 4'),
    )
    nom = models.CharField(verbose_name=u"Nom", max_length=255)
    image = models.ImageField(verbose_name=u"Image/Logo", upload_to="images/urgences/", blank=True)
    classe = models.CharField(verbose_name=u'Classe (CSS)', max_length=100, blank=True, choices=CSS)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Niveau d'urgence"
        verbose_name_plural=u"Niveaux d'urgence"


class Natures(models.Model):
    """ La table Natures liste les matrices (nature des spécimens à analyser) """
    nom = models.CharField(verbose_name=u"Nom", max_length=255)
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Nature de spécimen (matrice)"
        verbose_name_plural=u"Natures de spécimen (matrices)"


class Recommandations(models.Model):
    """ La table Recommandations contient les recommandations utiles pour le prélèvement.
    Quatre classes CSS sont proposées pour la mise en forme."""
    CSS = (
       ('recom1',u'recom 1'),
       ('recom2',u'recom 2'),
       ('recom3',u'recom 3'),
       ('recom4',u'recom 4'),
    )
    nom = models.CharField(verbose_name=u"Nom", max_length=255)
    image = models.ImageField(verbose_name=u"Image/Logo", upload_to="images/recommandations/", blank=True)
    classe = models.CharField(verbose_name=u'Classe (CSS)', max_length=100, blank=True, choices=CSS, default='recom1')
    date_modif = models.DateTimeField(verbose_name=u"Date de la dernière modification", auto_now=True,)
    def __unicode__ (self):
        return self.nom
    class Meta:
        verbose_name=u"Recommandation pour le prélèvement"
        verbose_name_plural=u"Recommandations pour le prélèvement"



class Examens(models.Model):
    """ La table Examens est la table centrale du système, elle regroupe les examens disponibles """
    nom          = models.CharField(verbose_name=u"Nom de l'examen", unique=True, null=False, max_length=255)
    date_activation = models.DateField(verbose_name=u"Date d'activation",default=lambda: datetime.datetime.now())
    date_desactivation = models.DateField(verbose_name=u"Date de désactivation",default=lambda: datetime.datetime.now()+datetime.timedelta(days=110000))
    code_sil     = models.CharField(verbose_name=u"Code SIL", max_length=255, blank=True, null=True)
    secteur      = models.ForeignKey('Secteurs', blank=True, null=True, on_delete=models.PROTECT)
    methode      = models.ForeignKey('Methodes', blank=True, null=True, on_delete=models.PROTECT)
    nature       = models.ForeignKey('Natures', blank=True, null=True, verbose_name=u"Nature du spécimen (matrice)")
    fichier      = models.ManyToManyField('Fichiers', verbose_name=u"Fichier(s) joint(s)", blank=True)
    urgence      = models.ForeignKey('Urgences',verbose_name=u"Peut-être demandé en urgence", blank=True, null=True)
    bon          = models.ForeignKey('Bons', blank=True, null=True, on_delete=models.PROTECT)
    actes        = models.ManyToManyField('Actes', through='Facturation', verbose_name=u'Actes', blank=True)
    delai_rendu  = models.SmallIntegerField(verbose_name=u"Délai (en heures) de rendu du résultat", blank=True, null=True)
    delai_recept = models.SmallIntegerField(verbose_name=u"Délai (en heures) après le prélèvement", blank=True, null=True)
    delai_preana = models.SmallIntegerField(verbose_name=u"Délai (en heures) après le préanalytique", blank=True, null=True)
    recommandations  = models.ForeignKey(Recommandations, verbose_name=u"Recommandations pour le prélèvement", blank=True, null=True)
    commentaire  = models.TextField(verbose_name=u"Commentaire", blank=True, null=True)
    indications  = models.TextField(verbose_name=u"Indications de l'examen", blank=True, null=True)
    acheminements = models.ForeignKey('Acheminements', blank=True, null=True, on_delete=models.PROTECT)
    soustraitance = models.OneToOneField(SousTraitance, verbose_name=u"Sous-traitance", blank=True, null=True)

pages/models.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models

import datetime
# Create your models here.


class Pages(models.Model):
    """ Les pages permettent de référencer des informations statiques (c-à-d qui changent peu souvent).
    Un lien est automatiquement ajouté dans le menu principal lorsque la date courrante est située entre les dates
    de début de de fin."""
    titre = models.CharField(max_length=250, unique=True, null=False, verbose_name=u'Titre')
    titre_court = models.CharField(max_length=50, unique=True, null=False, verbose_name=u'Titre court (apparaît dans le menu)')
    contenu = models.TextField(verbose_name=u'Contenu')
    date_debut = models.DateTimeField(verbose_name=u"Afficher dans le menu à partir du", default=lambda: datetime.datetime.now())
    date_fin = models.DateTimeField(verbose_name=u"Afficher dans le menu jusqu'au",default=lambda: datetime.datetime.now()+datetime.timedelta(days=365))
    def __unicode__ (self):
       return self.titre
    class Meta:
       verbose_name=u"Page"
       verbose_name_plural=u"Pages"

class News(models.Model):
     """ Les news s'affichent sur la page d'acceuil et permettent de proposer une information."""
     titre = models.CharField(max_length=250, unique=True, null=False, verbose_name=u'Titre')
     contenu = models.TextField(verbose_name=u'Contenu')
     date_debut = models.DateTimeField(verbose_name=u"Afficher à partir du", default=lambda: datetime.datetime.now())
     date_fin = models.DateTimeField(verbose_name=u"Afficher jusqu'au",default=lambda: datetime.datetime.now()+datetime.timedelta(days=14))
     def __unicode__ (self):
        return self.titre
     class Meta:
        verbose_name=u"Nouvelle"
        verbose_name_plural=u"Nouvelles"

ekz/forms.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django import forms

class RechercheForm(forms.Form):
    ChaineRecherche = forms.CharField(max_length=255, label='Examen à rechercher', required=True )

ekz/templates/base_colorbox.html
{% load static %}
<!DOCTYPE html>
<html id="colorbox">
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="{% static 'styles.css' %}" />
<link rel="stylesheet" href="{% static 'colorbox/colorbox.css' %}" />
<link rel="stylesheet" href="{% static 'perso.css' %}" />
<link rel="shortcut icon" type="image/png" href="{{ URL_FAVICON }}" />
<script type="text/JavaScript" src="{% static 'lib.js' %}"></script>
<script type="text/JavaScript" src="{% static 'jquery/jquery.js' %}"></script>
<script type="text/JavaScript" src="{% static 'colorbox/jquery.colorbox.js' %}"></script>
<script>
/* Description des effets colorbox */
$(document).ready(function(){
	$(".inline").colorbox({inline:true, width:"50%"});
});
</script>
<title>
{#    {% block title %}{{ TITRE_1 }} / {{ TITRE_2 }} {% endblock %}   #}
Le titre de la page HTML ici
</title>

</head>
<body{% block idBODY %}{% endblock %}>

<section id="content">
    {% block content %}{% endblock %}
</section>
</body>
</html>

ekz/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block idBODY %} id="index"{% endblock %}
{% block title %} {{ TITRE_3|striptags }} {% endblock %}
{% block header %}
<h3>{{ TITRE_3 }}</h3>
{% endblock %}

{% block content %}
    <article id="news">
    {% for new in news %}
        <fieldset class="cesure">
            <legend>
            {% if perms.pages.change_news %}
                <a href="{% url "admin:pages_news_change" new.id %}"><img src="{% static "img/editer.png" %}" alt="Modifier" title="Modifier cette new"></a>
            {% endif %}
                {{ new.titre }}
            </legend>
            {{ new.contenu|safe }}
        </fieldset>
        {% empty %}
        <fieldset style="border:none;"></fieldset>
    {% endfor %}
    </article>

{% endblock %}

ekz/templates/liste_alpha_examens.html
{% extends "base.html" %}

{% block idBODY %} id="liste_alpha_examens"{% endblock %}
{% block title %} Liste des examens / {{ lettre }}{% endblock %}
{% block header %}
<h3>Référentiel des examens </h3>
{% endblock %}

{% block content %}

<h2>Liste des examens commençant par la lettre {{ lettre }}</h2>

{% if Tout %}
   <ul class="clear">
     {% for un in Tout %}
        {% if un.examen.id %}
           <li>{{ un.nom|safe }} : voir <a href='{% url "voir_examen" un.examen.id %}'>{{ un.examen|safe }}</a></li>
        {% else %}
           <li><a href='{% url "voir_examen" un.id %}'>{{ un.nom|safe }}</a></li>
        {% endif %}
     {% endfor %} 
   </ul>
{% else %}
<p>Il n'y a rien pour l'instant.</p>
{% endif %}

{% endblock %}

ekz/templates/liste_bons.html
{% extends "base.html" %}

{% block idBODY %} id="liste_bons"{% endblock %}
{% block title %} Formulaires de prescription {% endblock %}
{% block header %}
<h3>Formulaires de prescription</h3>

{% endblock %}

{% block content %}

<ul class="liste_bons">
    {% for bon in liste_bons %}
        <li>
            {% if bon.image %}<img src="{{ MEDIA_URL }}{{ bon.image }}" alt="">{% endif %}
            {{ bon.nom }}.
            {% if bon.fichier %}<a href="{{ MEDIA_URL }}{{ bon.fichier }}">Télécharger</a>{% endif %}
        </li>
    {% empty %}
        <li>Rien n'a été paramétré pour l'instant.</li>
    {% endfor %}


</ul>


{% endblock %}

ekz/templates/liste_examens.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="liste_examens"{% endblock %}
{% block title %} Liste des examens {% endblock %}
{% block header %}
<h3>Liste des examens</h3>
{% endblock %}

{% block content %}
<p class="pagination">
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><img src="{% static 'img/precedent.png' %}" alt="Précédents" title="Page précédente"></a>
{% endif %}
Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><img src="{% static 'img/suivant.png' %}" alt="Suivants" title="Page suivante"></a>
{% endif %}
</p>

{% for examen in liste_examens %}

{% if perms.ekz.view_inactif and not examen.is_actif or examen.is_actif %}

<h3 class="{% if examen.is_actif %}actif{% else %}inactif{% endif %}">{{ examen.nom|safe }}
    {% if perms.ekz.change_examens %}
        <a href="{% url "admin:ekz_examens_change" examen.id %}"><img src="{% static "img/editer.png" %}" alt="Modifier" title="Modifier cet examen"></a>
    {% endif %}
<a href='{% url "voir_examen" examen.id %}'><img src="{% static 'img/details.png' %}" alt="Détails" title="Voir les détails"></a>
</h3>


{% if examen.synonymes.all %}<p>Synonymes : {% for synonyme in examen.synonymes.all %} {{ synonyme }} {% endfor %}</p>{% endif %}
{% if examen.indications %}<p>{{ examen.indications|truncatewords_html:20|safe }}</li>{% endif %}

<ul>
{% if examen.code_sil %}<li>SIL : {{ examen.code_sil }}</li>{% endif %}
{% if examen.secteur %}<li>Secteur : {{ examen.secteur }}</li>{% endif %}
{% if examen.soustraitance %}<li>Sous-traitance : {{ examen.soustraitance }}</li>{% endif %}
{% if examen.urgence %}<li>Urgence : {{ examen.urgence }}</li>{% endif %}
{% if examen.bon %}<li>Bon : {{ examen.bon }}</li>{% endif %}
{% if examen.acte %}<li>Coût : {{ examen.acte }}</li>{% endif %}

</ul>

{% endif %}
{% empty %}
<p> Il n'y a rien pour l'instant !</p>

{% endfor %}


<p class="pagination">
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><img src="{% static 'img/precedent.png' %}" alt="Précédents" title="Page précédente"></a>
{% endif %}
Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><img src="{% static 'img/suivant.png' %}" alt="Suivants" title="Page suivante"></a>
{% endif %}
</p>



{% endblock %}

ekz/templates/liste_prelevements.html
{% extends "base.html" %}

{% block idBODY %} id="liste_prelevements"{% endblock %}
{% block title %} Prélèvements {% endblock %}
{% block header %}
<h3>Aide au prélèvement</h3>
{% endblock %}

{% block content %}
<p>L'ordre tient compte de l'ordre de prélèvement des tubes</p>

<dl class="liste_prelevements">
    {% for prelevement in liste_prelevements %}
        <dt>{{ prelevement.nom }} : </dt>
        <dd>{{ prelevement.nombre }} {{ prelevement.tube }} {{ prelevement.ImgTubes|safe }}
                <ul>
                {% for examen in prelevement.examen.all %}
                    <li><a href="{% url 'voir_examen' examen.id %}">{{ examen.nom|safe }}</a></li>
                {% endfor %}
                </ul>
        </dd>
    {% empty %}
        <li>Rien n'a été paramétré pour l'instant.</li>
    {% endfor %}
</dl>


{% endblock %}

ekz/templates/liste_tubes.html
{% extends "base.html" %}

{% block idBODY %} id="liste_tubes"{% endblock %}
{% block title %} Tubes {% endblock %}
{% block header %}
<h3>Symboles des recueils pour les prélèvements</h3>
{% endblock %}

{% block content %}


<ul class="liste_tubes">
    {% for tube in liste_tubes %}
    <li><img src="{{ MEDIA_URL }}{{ tube.image }}" alt="{{ tube.nom }}">{{ tube.nom }}. Ordre : {{ tube.ordre }}</li>
    {% empty %}
        <li>Rien n'a été paramétré pour l'instant.</li>
    {% endfor %}


</ul>


{% endblock %}

ekz/templates/login.html
{% extends "base.html" %}

{% block idBODY %} id="login"{% endblock %}
{% block header %}
<h2>Connexion</h2>
{% endblock %}

{% block content %}

<fieldset>
    <legend>Identification</legend>
    {% if form.errors %}
        <p class="erreur">Nom d'utilisateur et/ou mot de passe incorrect.</p>
    {% endif %}
    {% include 'form_login.html' %}
</fieldset>
{% endblock %}

ekz/templates/login_colorbox.html
{% extends "base_colorbox.html" %}

{% block idBODY %} id="login_colorbox"{% endblock %}
{% block header %}
{% endblock %}

{% block content %}

    {% if form.errors %}
        <p class="erreur">Nom d'utilisateur et/ou mot de passe incorrect.</p>
    {% endif %}
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
            {{ form.username.label_tag }} {{ form.username }}
            <br>
            {{ form.password.label_tag }} {{ form.password }}
        <input type="submit" value="Connexion" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
<script language="JavaScript">
document.getElementById('id_username').focus();
</script>
{% endblock %}

ekz/templates/recherche.html
{% extends "base.html" %}
{% load static %}

{% block idBODY %} id="recherche"{% endblock %}
{% block title %} Rechercher {% endblock %}
{% block header %}
<h3>Recherche</h3>
{% endblock %}

{% block content %}

<fieldset>
    <legend><img src="{% static "img/loupe.png" %}" alt="Rechercher…"></legend>
           {% if form.errors %}
        <p class="erreur">Le formulaire contient des erreurs</p>
    {% endif %}
    <form method="get" action="{% url 'ekz.views.recherche' %}">
        {#% csrf_token %#}
        {{ form }}
        <input type="submit" value="Rechercher" />
    </form>
</fieldset>

{% if Resultats %}
<fieldset>
    <legend>Résultats</legend>
    <ul id="resultats">
    {% for res in Resultats %}
        <li>
           {% if res.examen.id %}
              {{ res.nom }} ; voir : <a href='{% url "voir_examen" res.examen.id %}' title="{{ res.examen.nom }}">{{ res.examen.nom }}</a>
           {% else %}
              <a href='{% url "voir_examen" res.id %}' title="{{ res.nom }}">{{ res.nom }}</a>
           {% endif %}
       </li>
    {% endfor %}
    </ul>
</fieldset>
{% elif ChaineRecherche %}
<p>Malheureusement, aucun résultat :-(</p>
{% endif %}


<script language="JavaScript">
document.getElementById('id_ChaineRecherche').focus();
</script>
{% endblock %}