ekz/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekz.views import ListeExamens, VoirExamen, liste_alpha_examens, accueil, ListeTubes, ListeBons, ListePrelevements, recherche

from django.contrib.auth.decorators import  permission_required


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

app_name = 'ekz'

urlpatterns =[
    # La liste des examens (tous)
    url(r'^$', ListeExamens.as_view(paginate_by=10), name='liste_examens'),

    # La liste des tubes (tous)
    url(r'^recueils/$', ListeTubes.as_view(), name='liste_tubes'),

    # La liste des bons (tous)
    url(r'^formulaires_de_prescription/$', ListeBons.as_view(), name='liste_bons'),

    # La liste des prelevements (tous)
    url(r'^aide_au_prelevement/$', ListePrelevements.as_view(), name='liste_prelevements'),

    # Page d'un examen
    url(r'^voir/(?P<pk>\d+)$', VoirExamen.as_view(),name='voir_examen'),

    # Liste alphabétique par lettre
    url(r'^commencent_par_(?P<lettre>.+)/$', liste_alpha_examens, name='liste_alpha_examens'),   # def liste_alpha_examens dans views.py

    # Page de recherche
    url(r'^rechercher/$', recherche, name='recherche'),

    # OpenSearch.xml
    url('^opensearch.xml$', TemplateView.as_view(template_name='opensearch.xml'), name='opensearch'),

]

ekzamenoj/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2014  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from ekzamenoj import configlocale
from ekz.views import accueil
from django.contrib.auth.views import login, logout


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns =[
    # Examples:
    # url(r'^$', 'ekzamenoj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Page d'accueil (i.e. « home »)
    url(r'^$', accueil, name='accueil'),

    url('^examens/', include('ekz.urls')),
    url('^page', include('pages.urls')),
    url('^patient/', include('patients.urls')),

    url(r'^summernote/', include('django_summernote.urls')),

    # Admindoc
    url(r'^' + settings.ADMIN_URL + '/doc/', include('django.contrib.admindocs.urls')),

    url(r'^' + settings.ADMIN_URL + '/', include(admin.site.urls)),

    # Login à part (provisoire ?)
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),

    # Déconnexion (nécessaire pour les utilisateurs n'ayant pas le statut équipe)
    url(r'^logout/$', logout, {'next_page': 'accueil'}, name='logout'),

    # Page test presc
    #url(r'^prescription/$', prescrire, name='prescrire'),

    # Fichiers robots.txt
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if configlocale.CONFIG_LOCALE['VOIR_PRESCRIPTIONS'] == True:
    urlpatterns +=[ 
        url('^prescriptions/', include('presc.urls')),
        ]

pages/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, include, url

from pages.views import VoirPage

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'pages'

urlpatterns = [

   # Une page
    url(r'^(?P<pk>\d+)$', VoirPage.as_view(),name='voir_page'),

]

patients/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url



from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

#from django.contrib.auth.decorators import  permission_required


from patients.views import PatientCreate, PatientView, Liste, recherche


app_name = "patients"
urlpatterns = [
       # La liste des patients
       #url(r'^$',Liste.as_view(), name='liste_patients'),

       # Page de recherche
       url(r'^$', recherche, name='recherche'),
       #url(r'^rechercher/$', recherche, name='recherche'),

       # Créer un nouveau patient
       url(r'^creer$', PatientCreate.as_view(), name='creer_patient'),

       # Voir le détail d'un patient
       url(r'^voir/(?P<pk>\d+)$', PatientView.as_view(), name='voir_patient'),


       ]

presc/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright (C) 2015  Nicolas Grandjean <nicolas@microniko.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.decorators import  permission_required

from presc.views import voir, Liste, prescrire, en_cours, vider, valider, enlever_examen, associer_patient, enlever_patient, eti_presc, prescrire_bilan, prelever, envoyer, recevoir


app_name = "presc"
urlpatterns = [
       # La liste des prescriptions (tous)
       url(r'^$', permission_required('presc.view_prescriptions',raise_exception=True)(Liste.as_view()), name='liste'),

       # Page d'une prescription
       url(r'^(?P<id>\d+)$', permission_required('presc.view_prescriptions',raise_exception=True)(voir), name='voir'),

       # PDF des étiquettes prescription
       url(r'^etiquettes/(?P<pk>\d+)\.pdf$', permission_required('presc.view_prescriptions',raise_exception=True)(eti_presc), name='etiquettes'),

       # Ajouter à une prescription
       url(r'^prescrire/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire), name='prescrire'),

       # Ajouter un bilan à une prescription
       url(r'^prescrire/bilan/(?P<bilan_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(prescrire_bilan), name='prescrire_bilan'),

       # Enlever d'une prescription
       url(r'^enlever/(?P<examen_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_examen), name='enlever_examen'),

       # Enlever le patient de la prescription en cours de saisie (doit être déclaré avant l'attribution)
       url(r'^patient/enlever$', permission_required('presc.create_prescriptions',raise_exception=True)(enlever_patient), name='enlever_patient'),

       # Attribuer une prescription à un patient
       url(r'^patient/(?P<patient_id>\d+)$', permission_required('presc.create_prescriptions',raise_exception=True)(associer_patient), name='associer_patient'),

       # Détail de la prescription en cours de saisie
       url(r'^voir$', permission_required('presc.create_prescriptions',raise_exception=True)(en_cours), name='prescription'),

       # Vider la prescription en cours de saisie
       url(r'^vider$', permission_required('presc.create_prescriptions',raise_exception=True)(vider), name='vider'),

       # Valider la prescription en cours de saisie
       # Le décorateur de permission ne peut pas être ici (pourquoi ?) il est donc dans views.py
       url(r'^valider$', valider, name='valider'),
       #url(r'^valider$', permission_required('presc.create_prescriptions',raise_exception=True)(valider), name='valider'),

       # Prélever une prescription
       url(r'^prelever/(?P<prescription_id>\d+)$', permission_required('presc.prelever_prescriptions',raise_exception=True)(prelever), name='prelever'),

       # Envoyer une prescription
       url(r'^envoyer/(?P<prescription_id>\d+)$', permission_required('presc.envoyer_prescriptions',raise_exception=True)(envoyer), name='envoyer'),

       # Recevoir une prescription
       url(r'^recevoir/(?P<prescription_id>\d+)$', permission_required('presc.recevoir_prescriptions',raise_exception=True)(recevoir), name='recevoir'),

       ]

templates/base.html
{% load static %}
{% get_media_prefix as MEDIA_URL %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="{% static 'styles.css' %}" />
<link rel="stylesheet" href="{% static 'perso.css' %}" />
<link rel="shortcut icon" type="image/png" href="{{ URL_FAVICON }}" />
<link rel="search" type="application/opensearchdescription+xml" title="Recherche d'examens de biologie" href="{% url 'ekz:opensearch' %}" />
<link rel="stylesheet" href="{% static 'jquery-ui-themes/themes/smoothness/jquery-ui.min.css' %}">
<script type="text/JavaScript" src="{% static 'jquery/jquery.js' %}"></script>
<script type="text/JavaScript" src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script type="text/JavaScript" src="{% static 'lib.js' %}"></script>


<title>{{ TITRE_1|striptags }} /
    {% block title %} {{ TITRE_2|striptags }} {% endblock %}
</title>

</head>
<body{% block idBODY %}{% endblock %}>

<header>
    <a href="/"><img src="{{ URL_LOGO }}" alt="{{ ALT_LOGO }}" title="{{ TITLE_LOGO }}"></a>
    <h1>{{ TITRE_1|safe }}</h1>
    <h2>{{ TITRE_2|safe }}</h2>
    {% block header %} En-tête ... {% endblock %}
</header>

<nav>
<ul>
    <li><a href="/">Accueil</a></li>
    <li><a href='{% url 'ekz:recherche' %} '>Rechercher</a></li>
    {% block nav %}
    {% endblock %}
    {% for page in pages %}
        <li><a href='{% url "pages:voir_page" page.id %}' title="{{ page.titre }}">{{ page.titre_court }}</a></li>
    {% endfor %}
    <li><a href='{% url "ekz:liste_tubes" %}'>Recueils</a></li>
    {% if VOIR_LISTE_DES_BONS == True %}
    <li><a href='{% url "ekz:liste_bons" %}'>Formulaires de prescription</a></li>
    {% endif %}
    <li><a href='{% url "ekz:liste_prelevements" %}'>Aide au prélèvement</a></li>
    {% if VOIR_PRESCRIPTIONS == True  and perms.presc.view_prescriptions %}
    <li><a href='{% url "presc:liste" %}'>Prescriptions</a></li>
    {% if perms.presc.create_prescriptions %}
    <li><a href='{% url "presc:prescription" %}'>Prescription</a></li>
    {% endif %}
    <li><a href="{% url 'patients:recherche' %}">Patients</a></li>
    {% endif %}
</ul>
<ul id="user">
    {% if user.is_authenticated %}
        <li>Bonjour {{ user.first_name }} {{ user.last_name }}
            {% if user.groups.all %}
                <em>({% for groupe in user.groups.all %}{{groupe.name }}{% if not forloop.last %}, {% endif %}{% endfor %})</em>
            {% endif %}
        </li>
        <li>
            {% if user.is_staff %}
            <a href="{% url "admin:index" %}"><img src="{% static 'img/admin2.png' %}" title="Administration" alt="Administration">Administration</a>{% endif %}
            <a href="{% url 'logout' %}"><img src="{% static 'img/logout.png' %}" alt="Déconnexion" title="Se déconnecter">Déconnexion</a>
            {% else %}
        </li>
        <li>
            <a href="{% url 'login' %}"><img src="{% static 'img/login.png' %}" title="Se connecter" alt="Connexion"></a>
            <div id="formulaire_login">
            {% include 'form_login.html' %}
            </div>
        </li>
    {% endif %}
</ul>

</nav>

<section id="content">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{% if message.tags %} {{ message.tags }} {% else %} info{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% block content %}{% endblock %}
</section>

<aside>
    {% block aside %}{% endblock %}
    {% if alphabet %}
    <ul class="alphabet">
        {% for l in alphabet %}
        <li{% if lettre == l %} class="actif" {% endif %}><a href='{% url "ekz:liste_alpha_examens" l %}'>{{ l }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</aside>


<footer class="clear">
<p>{% now "DATETIME_FORMAT" %} - <a href="#oModalInfosEkz" title="Voir plus d'informations">Fonctionne avec Ekzamenoj</a></p>


{% include "omodal_haut.html" with id="oModalInfosEkz" %}
    <p><em>Ekzamenoj</em> est un Logiciel Libre. <a href="https://git.framasoft.org/microniko/ekzamenoj">Sources</a>.
    </p>
    <h1>
    Version
    </h1>
    <p>
    Ekzamenoj {{ version }} {% if django %} - Django {{ django }} {% endif %} {% if python %} - {{ python }} {% endif %}
    </p>
    {% if user.is_staff %}
    <h1>
        Informations
    </h1>
    <table>
    <thead>
        <tr>
            <td>Applications installées</td>
            <td>Environnement</td>
        </tr>
    </thead>
    <tbody>
        <tr class="code">
            <td><code>settings.py</code></td>
            <td><code>pip freeze</code></td>
        </tr>
        <tr>
            <td>
                <ul>
                {% for x in apps %}
                    <li>{{ x }}</li>
                {% endfor %}
                </ul>
            </td>
            <td>
                {{ pip|linebreaksbr }}
            </td>
        </tr>
    </tbody>
    </table>
    {% endif %}
    <h1>
        Licence
    </h1>
    <p>
    Ce logiciel est fourni tel quel <strong>sans aucune garantie</strong> et dans l’espoir qu’il pourrait être utile.
    </p>
    <p>
    Ce logiciel est sous licence AGPL (GNU AFFERO GENERAL PUBLIC LICENSE) version 3. Il peut-être utilisé, modifié, étudié, et redistribué (à condition de le faire dans la même licence ou dans une licence compatible). Vous pouvez trouver la version intégrale de cette licence sur le site de la <a href="http://www.gnu.org/licenses/agpl.html">Free Software Foundation</a>.
    </p>
{% include "omodal_bas.html" with id="oModalInfosEkz" legende="Informations" %}
</footer>


<script type="text/JavaScript">
/* On ferme les oModal si on presse la touche Echap */
window.addEventListener("keydown", function(e) {
    if (e.keyCode == 27) {
        document.location = '#ferme';
    }
});

</script>
</body>
</html>

templates/form_login.html
<!--
Formulaire de login
 -->
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <ul>
	{% comment "Il faudrait pouvoir utiliser ↓↓↓↓ ?" %}
            <li>{{ form.username.label_tag }} {{ form.username }}</li>
            <li>{{ form.password.label_tag }} {{ form.password }}</li>
	{% endcomment %}
	    <li><input id="id_username" maxlength="254" name="username" type="text" placeholder="Nom d'utilisateur"></li>
	    <li><input id="id_password" name="password" type="password" placeholder="Mot de passe"></li>
        </ul>
        <input type="submit" value="Connexion" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>